name: Run Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.rst'
      - '**.md'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - '.readthedocs.yaml'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-22.04  # 3.7 needs 22.04, can move to -latest when we drop 3.7 support
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    - name: Clone ocs
      uses: actions/checkout@v6

    - name: Install ocs
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .[so3g]

    - name: Run unit tests
      working-directory: ./tests
      run: |
        COVERAGE_FILE=.coverage.unit-${{ matrix.python }} python3 -m pytest --cov -m 'not integtest'

    - name: Upload coverage file artifact
      uses: actions/upload-artifact@v7
      with:
        name: coverage-${{ matrix.python }}
        include-hidden-files: true
        path: ./tests/.coverage.*

  integ-test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
    # Run on a single version, since these tests are run in Docker
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Clone ocs
      uses: actions/checkout@v6

    - name: Install ocs
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .[so3g]

    - name: Build images for integration tests
      run: |
        docker compose build ocs ocs-crossbar

    - name: Run integration tests
      working-directory: ./tests
      run: |
        mkdir log
        COVERAGE_FILE=.coverage.int python3 -m pytest --cov -m 'integtest'
        ls -la ./log/

    - name: Upload coverage file artifact
      uses: actions/upload-artifact@v7
      with:
        name: coverage-integ
        include-hidden-files: true
        path: ./tests/.coverage.*

  upload-coverage:
    name: Upload coverage
    needs: [unit-test, integ-test]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Install coverage
      run: |
        python -m pip install coverage

    # Coverage report doesn't work unless we have a checkout
    - name: Clone ocs
      uses: actions/checkout@v6

    # Download after checkout, else artifacts get deleted
    - name: Download coverage artifacts
      uses: actions/download-artifact@v8

    - name: List coverage output for upload
      run: |
        ls -lthra
        ls -lthra coverage*
        pwd

    - name: Report test coverage
      run: |
        mv ./coverage-*/.coverage.* ./
        coverage combine
        coverage xml
        coverage report

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
