name: Run Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.rst'
      - '**.md'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - '.readthedocs.yaml'
  workflow_call:

jobs:
  test:
    name: pytest with coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
    # Setup
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.13.0
      with:
        access_token: ${{ github.token }}

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    # Install
    - name: clone ocs
      uses: actions/checkout@v6

    - name: Install ocs
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .[so3g]

    # Unit Tests
    - name: Run unit tests
      working-directory: ./tests
      run: |
        COVERAGE_FILE=.coverage.unit-${{ matrix.python }} python3 -m pytest --cov -m 'not integtest'

    - name: Checkout coverage output for upload
      run: |
        ls -lthra
        pwd
