name: Run Tests

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**.rst'
      - '**.md'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - '.readthedocs.yaml'

jobs:
  unit-test:
    name: Run unit tests (3.12)
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '

  integ-test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
